version: '2.1'
orbs:
    browser-tools: circleci/browser-tools@1.4.6

executors:
    percy-executor:
        docker:
            - image: percyio/agent
              auth:
                  username: dashautomation
                  password: $DASH_PAT_DOCKERHUB
    node-executor:
        docker:
            - image: cimg/node:20.5.1
              auth:
                  username: dashautomation
                  password: $DASH_PAT_DOCKERHUB
    python-3-11-executor:
        docker:
            - image: cimg/python:3.11.5-browsers
              auth:
                  username: dashautomation
                  password: $DASH_PAT_DOCKERHUB
    python-3-8-executor:
        docker:
            - image: cimg/python:3.8.18-browsers
              auth:
                  username: dashautomation
                  password: $DASH_PAT_DOCKERHUB

jobs:
    percy-finalize:
        executor: percy-executor
        steps:
            - run: percy finalize --all
    node:
        executor: node-executor
        steps:
            - checkout
            - run:
                  name: Install package.json
                  command: npm i

            - save_cache:
                  key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
                  paths:
                      - node_modules

            - run:
                  name: Run eslint
                  command: npm run lint.eslint
                  when: always

            - run:
                  name: Run prettier
                  command: npm run lint.prettier
                  when: always

    python-3-11: &test-template
        executor: python-3-11-executor

        environment:
            PERCY_ENABLED: True
            PERCY_PARALLEL_TOTAL: -1

        steps:
            - checkout
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver

            - restore_cache:
                  key: deps1-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}

            - run:
                  name: Create virtualenv
                  command: rm -rf venv && python -m venv venv

            - run:
                  name: Install requirements
                  command: . venv/bin/activate && pip install -r tests/requirements.txt

            - save_cache:
                  key: deps1-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
                  paths:
                      - 'venv'

            - run:
                  name: Run lint for Python files
                  command: |
                      . venv/bin/activate
                      npm run lint:python
                  when: always

            - run:
                  name: Integration Tests - Usage Apps Rendering
                  command: |
                      . venv/bin/activate
                      pytest --nopercyfinalize --headless tests/test_usage.py
                  when: always

            - run:
                  name: Integration Tests - Interactions
                  command: |
                      . venv/bin/activate
                      pytest --headless tests/test_interactions.py
                  when: always

            - run:
                  name: Integration Tests - Callbacks
                  command: |
                      . venv/bin/activate
                      pytest --headless tests/test_callbacks.py
                  when: always

            - run:
                  name: Capture Percy Snapshots
                  command: |
                      . venv/bin/activate
                      pytest --headless tests/test_percy_snapshot.py
                  when: always

    python-3-8:
        <<: *test-template
        executor: python-3-8-executor

        environment:
            PERCY_ENABLE: False

    python-3-11-react-18:
        <<: *test-template
        executor: python-3-11-executor

        environment:
            PERCY_ENABLE: False
            REACT_VERSION: '18.2.0'

workflows:
    version: 2.1
    build:
        jobs:
            - python-3-11
            - python-3-8
            - python-3-11-react-18
            - node
            - percy-finalize:
                  requires:
                      - python-3-11
